export const dfconnectProductionManifest = {
  schema: "public-delivery-manifest-v1",
  siteId: "dfconnect",
  environment: "production",
  allowedOrigins: [
    "https://dfconnect.jp",
    "https://www.dfconnect.jp",
  ],
  checks: [
    {
      checkId: "public.dns.apex",
      kind: "dns",
      url: "https://dfconnect.jp/",
      method: "HEAD",
      validForSeconds: 180,
      maxRedirects: 0,
      maxResponseBytes: 0,
      maxElapsedMs: 1_500,
      tlsMinDaysRemaining: 14,
      expect: {},
    },
    {
      checkId: "public.tls.apex",
      kind: "tls",
      url: "https://dfconnect.jp/",
      method: "HEAD",
      validForSeconds: 180,
      maxRedirects: 0,
      maxResponseBytes: 0,
      maxElapsedMs: 1_500,
      tlsMinDaysRemaining: 14,
      expect: {},
    },
    {
      checkId: "public.apex",
      kind: "http",
      url: "https://dfconnect.jp/",
      method: "GET",
      validForSeconds: 180,
      maxRedirects: 0,
      maxResponseBytes: 131_072,
      maxElapsedMs: 1_500,
      tlsMinDaysRemaining: 14,
      expect: {
        status: 200,
        contentTypePrefix: "text/html",
        bodyMarker: "Web運用の、",
        canonical: "https://dfconnect.jp/",
        requiredHeaders: ["x-content-type-options"],
      },
    },
    {
      checkId: "public.www",
      kind: "http",
      url: "https://www.dfconnect.jp/",
      method: "GET",
      validForSeconds: 180,
      maxRedirects: 1,
      maxResponseBytes: 131_072,
      maxElapsedMs: 1_500,
      tlsMinDaysRemaining: 14,
      expect: {
        status: 200,
        contentTypePrefix: "text/html",
        bodyMarker: "Web運用の、",
        canonical: "https://dfconnect.jp/",
        requiredHeaders: ["x-content-type-options"],
      },
    },
    {
      checkId: "public.pricing",
      kind: "http",
      url: "https://dfconnect.jp/pricing/",
      method: "GET",
      validForSeconds: 180,
      maxRedirects: 0,
      maxResponseBytes: 131_072,
      maxElapsedMs: 1_500,
      tlsMinDaysRemaining: 14,
      expect: {
        status: 200,
        contentTypePrefix: "text/html",
        bodyMarker: "料金一覧",
        canonical: "https://dfconnect.jp/pricing/",
        requiredHeaders: ["x-content-type-options"],
      },
    },
    {
      checkId: "public.not_found",
      kind: "http",
      url: "https://dfconnect.jp/__autoguard-not-found__",
      method: "GET",
      validForSeconds: 300,
      maxRedirects: 0,
      maxResponseBytes: 65_536,
      maxElapsedMs: 1_500,
      tlsMinDaysRemaining: 14,
      expect: {
        status: 404,
        contentTypePrefix: "text/html",
        bodyMarker: "ページが見つかりません",
        requiredHeaders: ["x-content-type-options"],
      },
    },
    {
      checkId: "public.robots",
      kind: "http",
      url: "https://dfconnect.jp/robots.txt",
      method: "GET",
      validForSeconds: 300,
      maxRedirects: 0,
      maxResponseBytes: 16_384,
      maxElapsedMs: 1_500,
      tlsMinDaysRemaining: 14,
      expect: {
        status: 200,
        contentTypePrefix: "text/plain",
        bodyMarker: "Sitemap: https://dfconnect.jp/sitemap.xml",
        requiredHeaders: ["x-content-type-options"],
      },
    },
    {
      checkId: "public.sitemap",
      kind: "http",
      url: "https://dfconnect.jp/sitemap.xml",
      method: "GET",
      validForSeconds: 300,
      maxRedirects: 0,
      maxResponseBytes: 262_144,
      maxElapsedMs: 1_500,
      tlsMinDaysRemaining: 14,
      expect: {
        status: 200,
        contentTypePrefix: "application/xml",
        bodyMarker: "<urlset",
        requiredHeaders: ["x-content-type-options"],
      },
    },
    {
      checkId: "public.known_asset",
      kind: "http",
      url: "https://dfconnect.jp/assets/images/dfconnect-mark.png",
      method: "GET",
      validForSeconds: 300,
      maxRedirects: 0,
      maxResponseBytes: 1_048_576,
      maxElapsedMs: 1_500,
      tlsMinDaysRemaining: 14,
      expect: {
        status: 200,
        contentTypePrefix: "image/png",
        requiredHeaders: ["x-content-type-options"],
      },
    },
  ],
} as const;
